// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ErrorResponseDto = {
    statusCode: number;
    message: string | Array<string>;
    error?: string;
    timestamp: string;
    path: string;
    correlationId?: string;
};

export type SignInDto = {
    email: string;
    password: string;
    rememberMe?: boolean;
};

export type RedirectTo = 'dashboard' | 'email-verification' | 'password-reset' | 'org-setup' | 'sign-in';

export type SignInResponseDto = {
    redirectTo: RedirectTo;
};

export type SignUpDto = {
    name: string;
    email: string;
    password: string;
};

export type SuccessResponseDto = {
    success: boolean;
    redirectTo?: RedirectTo;
};

export type SendEmailOtpDto = {
    email: string;
    type?: 'email-verification' | 'sign-in' | 'forget-password';
};

export type VerifyEmailOtpDto = {
    email: string;
    otp: string;
};

export type ForgotPasswordDto = {
    email: string;
};

export type ResetPasswordDto = {
    email: string;
    otp: string;
    password: string;
};

export type OrganizationCountry = 'IN' | 'US';

export type OrganizationCurrency = 'INR' | 'USD';

export type CreateOrganizationDto = {
    name: string;
    slug: string;
    timezone: string;
    country: OrganizationCountry;
    currency: OrganizationCurrency;
};

export type SetActiveOrganizationDto = {
    /**
     * Organization id to activate, or null to unset
     */
    organizationId?: {
        [key: string]: unknown;
    } | null;
    /**
     * Organization slug to activate when organizationId is omitted
     */
    organizationSlug?: string;
};

export type OrganizationVerificationStatus = 'not_started' | 'pending' | 'active' | 'rejected';

export type OrganizationCapabilitiesFlagsDto = {
    isKycVerified: boolean;
    canCollectOnlineDonations: boolean;
    canReceivePayouts: boolean;
    canRecordDonationsManually: boolean;
    canAddMembers: boolean;
    canInviteTeam: boolean;
    canManageFunds: boolean;
    canSubmitVerification: boolean;
};

export type OrganizationVerificationSummaryDto = {
    status: OrganizationVerificationStatus;
    statusAt?: string | null;
    rejectionReason?: string | null;
};

export type OrganizationCapabilitiesResponseDto = {
    organizationId: string;
    capabilities: OrganizationCapabilitiesFlagsDto;
    verification: OrganizationVerificationSummaryDto;
};

export type GetCurrentSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/session';
};

export type GetCurrentSessionErrors = {
    401: ErrorResponseDto;
};

export type GetCurrentSessionError = GetCurrentSessionErrors[keyof GetCurrentSessionErrors];

export type GetCurrentSessionResponses = {
    /**
     * Current user session
     */
    200: unknown;
};

export type SignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-in';
};

export type SignInErrors = {
    400: ErrorResponseDto;
    401: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type SignInError = SignInErrors[keyof SignInErrors];

export type SignInResponses = {
    /**
     * Sets pb_access_token, pb_refresh_token, and pb_session_token cookies when email is verified
     */
    200: SignInResponseDto;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];

export type SignUpData = {
    body: SignUpDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-up';
};

export type SignUpErrors = {
    400: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type SignUpError = SignUpErrors[keyof SignUpErrors];

export type SignUpResponses = {
    200: SignInResponseDto;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-out';
};

export type SignOutErrors = {
    400: ErrorResponseDto;
};

export type SignOutError = SignOutErrors[keyof SignOutErrors];

export type SignOutResponses = {
    200: SuccessResponseDto;
};

export type SignOutResponse = SignOutResponses[keyof SignOutResponses];

export type SendEmailOtpData = {
    body: SendEmailOtpDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email-otp/send';
};

export type SendEmailOtpErrors = {
    400: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type SendEmailOtpError = SendEmailOtpErrors[keyof SendEmailOtpErrors];

export type SendEmailOtpResponses = {
    200: SuccessResponseDto;
};

export type SendEmailOtpResponse = SendEmailOtpResponses[keyof SendEmailOtpResponses];

export type VerifyEmailOtpData = {
    body: VerifyEmailOtpDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email-otp/verify';
};

export type VerifyEmailOtpErrors = {
    400: ErrorResponseDto;
    401: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type VerifyEmailOtpError = VerifyEmailOtpErrors[keyof VerifyEmailOtpErrors];

export type VerifyEmailOtpResponses = {
    200: SignInResponseDto;
};

export type VerifyEmailOtpResponse = VerifyEmailOtpResponses[keyof VerifyEmailOtpResponses];

export type ForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type ForgotPasswordErrors = {
    400: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type ForgotPasswordError = ForgotPasswordErrors[keyof ForgotPasswordErrors];

export type ForgotPasswordResponses = {
    200: SuccessResponseDto;
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type ResetPasswordErrors = {
    400: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    200: SuccessResponseDto;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type ListOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organization';
};

export type ListOrganizationsErrors = {
    401: ErrorResponseDto;
};

export type ListOrganizationsError = ListOrganizationsErrors[keyof ListOrganizationsErrors];

export type ListOrganizationsResponses = {
    /**
     * Organizations the current user belongs to
     */
    200: unknown;
};

export type CreateOrganizationData = {
    body: CreateOrganizationDto;
    path?: never;
    query?: never;
    url: '/api/v1/organization';
};

export type CreateOrganizationErrors = {
    400: ErrorResponseDto;
    401: ErrorResponseDto;
};

export type CreateOrganizationError = CreateOrganizationErrors[keyof CreateOrganizationErrors];

export type CreateOrganizationResponses = {
    /**
     * Organization profile created
     */
    201: unknown;
};

export type GetOrganizationProfileData = {
    body?: never;
    path: {
        /**
         * Organization id
         */
        organizationId: string;
    };
    query?: never;
    url: '/api/v1/organization/{organizationId}/profile';
};

export type GetOrganizationProfileErrors = {
    401: ErrorResponseDto;
    404: ErrorResponseDto;
};

export type GetOrganizationProfileError = GetOrganizationProfileErrors[keyof GetOrganizationProfileErrors];

export type GetOrganizationProfileResponses = {
    /**
     * Organization profile
     */
    200: unknown;
};

export type GetOrganizationData = {
    body?: never;
    path: {
        /**
         * Organization id
         */
        organizationId: string;
    };
    query?: never;
    url: '/api/v1/organization/{organizationId}';
};

export type GetOrganizationErrors = {
    401: ErrorResponseDto;
    404: ErrorResponseDto;
};

export type GetOrganizationError = GetOrganizationErrors[keyof GetOrganizationErrors];

export type GetOrganizationResponses = {
    /**
     * Organization with profile
     */
    200: unknown;
};

export type SetActiveOrganizationData = {
    body: SetActiveOrganizationDto;
    path?: never;
    query?: never;
    url: '/api/v1/organization/activate';
};

export type SetActiveOrganizationErrors = {
    400: ErrorResponseDto;
    401: ErrorResponseDto;
};

export type SetActiveOrganizationError = SetActiveOrganizationErrors[keyof SetActiveOrganizationErrors];

export type SetActiveOrganizationResponses = {
    /**
     * Active organization updated; pb_access_token reminted with the new organizationId
     */
    200: unknown;
};

export type HealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/live';
};

export type HealthLiveErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: 'error' | 'shutting_down';
        info?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthLiveError = HealthLiveErrors[keyof HealthLiveErrors];

export type HealthLiveResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: 'ok' | 'degraded';
        info?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/ready';
};

export type HealthReadyErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: 'error' | 'shutting_down';
        info?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthReadyError = HealthReadyErrors[keyof HealthReadyErrors];

export type HealthReadyResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: 'ok' | 'degraded';
        info?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthReadyResponse = HealthReadyResponses[keyof HealthReadyResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: 'error' | 'shutting_down';
        info?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: 'ok' | 'degraded';
        info?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: 'up' | 'degraded' | 'down';
                /**
                 * Time the health indicator took to respond, in ms
                 */
                responseTime?: number;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type RefreshAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshAccessTokenErrors = {
    401: ErrorResponseDto;
    429: ErrorResponseDto;
};

export type RefreshAccessTokenError = RefreshAccessTokenErrors[keyof RefreshAccessTokenErrors];

export type RefreshAccessTokenResponses = {
    /**
     * Sets a fresh pb_access_token cookie
     */
    200: SuccessResponseDto;
};

export type RefreshAccessTokenResponse = RefreshAccessTokenResponses[keyof RefreshAccessTokenResponses];

export type GetOrganizationCapabilitiesData = {
    body?: never;
    path: {
        /**
         * Organization id
         */
        organizationId: string;
    };
    query?: never;
    url: '/api/v1/organization/{organizationId}/capabilities';
};

export type GetOrganizationCapabilitiesErrors = {
    401: ErrorResponseDto;
    404: ErrorResponseDto;
};

export type GetOrganizationCapabilitiesError = GetOrganizationCapabilitiesErrors[keyof GetOrganizationCapabilitiesErrors];

export type GetOrganizationCapabilitiesResponses = {
    /**
     * Organization capabilities
     */
    200: OrganizationCapabilitiesResponseDto;
};

export type GetOrganizationCapabilitiesResponse = GetOrganizationCapabilitiesResponses[keyof GetOrganizationCapabilitiesResponses];
